[package]
name = "peripheral_access"
version = "0.1.0"
authors = ["svd2rust"]

[dependencies]
bare-metal = "*"
cortex-m = "*"
vcell = "*"

[dependencies.cortex-m-rt]
optional = true
version = "*"

[features]
rt = ["cortex-m-rt/device"]
